"""Unit tests for simulations.envelope.

Each test focuses on one specific property. Irrelevant parameters are
generated via faker so every run acts as a light fuzz pass. Explicit
edge-case values (0.0, boundaries, etc.) are never generated by faker
in tests that are meant to cover ordinary behaviour - that way the edge
cases live in their own dedicated tests and the fuzz tests stay clean.
"""

import pytest
from faker import Faker
from simulations.envelope import (
    AMPLITUDE_LOWER_CUTOFF,
    AMPLITUDE_MAX,
    AMPLITUDE_MIN,
    INTERVAL_MAX,
    PROGRESS_MAX,
    PROGRESS_MIN,
    SHAPE_MAX,
    SHAPE_MIN,
    SLOPE_TIME_MIN,
    TIME_END,
    TIME_MIDPOINT,
    TIME_START,
    EnvelopeSettings,
    EnvelopeStatus,
    a_d_envelope,
    a_d_shape,
    combine_envelopes,
    combine_interpolate_linear,
    combine_max,
    offset_envelopes,
)

fake = Faker()

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _random_shape() -> float:
    """Random shape strictly inside valid range (excludes boundary values)."""
    return fake.pyfloat(min_value=0.001, max_value=0.999)


def _random_progress() -> float:
    """Random progress strictly inside valid range (excludes 0 and 1)."""
    return fake.pyfloat(min_value=0.001, max_value=0.999)


def _random_attack_decay() -> float:
    """Random attack or decay strictly inside (0, TIME_MIDPOINT)."""
    return fake.pyfloat(min_value=0.05, max_value=TIME_MIDPOINT - 0.05)


def _random_amplitude_enabled() -> float:
    """Random amplitude that is clearly enabled (well above the cutoff)."""
    return fake.pyfloat(min_value=AMPLITUDE_LOWER_CUTOFF + 0.05, max_value=0.95)


def _settings(
    *,
    attack: float | None = None,
    decay: float | None = None,
    shape: float | None = None,
    amplitude: float | None = None,
) -> EnvelopeSettings:
    """Build an EnvelopeSettings, using faker for any unspecified field."""
    return EnvelopeSettings(
        attack=attack if attack is not None else _random_attack_decay(),
        decay=decay if decay is not None else _random_attack_decay(),
        shape=shape if shape is not None else _random_shape(),
        amplitude=amplitude if amplitude is not None else _random_amplitude_enabled(),
    )


def _status(
    time: float, value: float, midpoint: float = TIME_MIDPOINT
) -> EnvelopeStatus:
    return EnvelopeStatus(time=time, midpoint=midpoint, value=value)


# ---------------------------------------------------------------------------
# Block A — a_d_shape()
# ---------------------------------------------------------------------------


class TestADShapeAssertions:
    def test_rejects_progress_below_min(self):
        shape = _random_shape()
        with pytest.raises(AssertionError):
            _ = a_d_shape(shape, PROGRESS_MIN - 0.001)

    def test_rejects_progress_above_max(self):
        shape = _random_shape()
        with pytest.raises(AssertionError):
            _ = a_d_shape(shape, PROGRESS_MAX + 0.001)

    def test_rejects_shape_below_min(self):
        progress = _random_progress()
        with pytest.raises(AssertionError):
            _ = a_d_shape(SHAPE_MIN - 0.001, progress)

    def test_rejects_shape_above_max(self):
        progress = _random_progress()
        with pytest.raises(AssertionError):
            _ = a_d_shape(SHAPE_MAX + 0.001, progress)


@pytest.mark.parametrize("shape", [0.0, 0.25, 0.5, 0.75, 1.0])
class TestADShapeEndpoints:
    def test_progress_zero_gives_zero(self, shape: float):
        assert a_d_shape(shape, 0.0) == 0.0

    def test_progress_one_gives_one(self, shape: float):
        assert a_d_shape(shape, 1.0) == pytest.approx(1.0)


class TestADShapeExtremes:
    def test_linear_at_shape_zero(self):
        progress = _random_progress()
        assert a_d_shape(0.0, progress) == pytest.approx(progress)

    def test_exponential_at_shape_one(self):
        progress = _random_progress()
        assert a_d_shape(1.0, progress) == pytest.approx(progress**10)


class TestADShapeMonotonicity:
    def test_monotonically_non_decreasing(self):
        shape = _random_shape()
        p1 = fake.pyfloat(min_value=0.001, max_value=0.498)
        p2 = fake.pyfloat(min_value=0.502, max_value=0.999)
        assert a_d_shape(shape, p1) <= a_d_shape(shape, p2) + 1e-12


class TestADShapeOutputRange:
    def test_output_in_unit_range(self):
        shape = _random_shape()
        progress = _random_progress()
        result = a_d_shape(shape, progress)
        assert 0.0 <= result <= 1.001


# ---------------------------------------------------------------------------
# Block B — EnvelopeSettings + is_disabled()
# ---------------------------------------------------------------------------


class TestEnvelopeSettingsAssertions:
    def test_rejects_negative_attack(self):
        with pytest.raises(AssertionError):
            _ = _settings(attack=-0.001)

    def test_rejects_attack_above_midpoint(self):
        with pytest.raises(AssertionError):
            _ = _settings(attack=TIME_MIDPOINT + 0.001)

    def test_rejects_negative_decay(self):
        with pytest.raises(AssertionError):
            _ = _settings(decay=-0.001)

    def test_rejects_decay_above_midpoint(self):
        with pytest.raises(AssertionError):
            _ = _settings(decay=TIME_MIDPOINT + 0.001)

    def test_rejects_shape_below_min(self):
        with pytest.raises(AssertionError):
            _ = _settings(shape=SHAPE_MIN - 0.001)

    def test_rejects_shape_above_max(self):
        with pytest.raises(AssertionError):
            _ = _settings(shape=SHAPE_MAX + 0.001)

    def test_rejects_amplitude_below_min(self):
        with pytest.raises(AssertionError):
            _ = _settings(amplitude=AMPLITUDE_MIN - 0.001)

    def test_rejects_amplitude_above_max(self):
        with pytest.raises(AssertionError):
            _ = _settings(amplitude=AMPLITUDE_MAX + 0.001)


class TestIsDisabled:
    def test_amplitude_zero_is_disabled(self):
        assert _settings(amplitude=0.0).is_disabled() is True

    def test_amplitude_at_lower_cutoff_is_disabled(self):
        assert _settings(amplitude=AMPLITUDE_LOWER_CUTOFF).is_disabled() is True

    def test_amplitude_just_above_cutoff_is_enabled(self):
        assert (
            _settings(amplitude=AMPLITUDE_LOWER_CUTOFF + 0.0001).is_disabled() is False
        )

    def test_midrange_amplitude_is_enabled(self):
        amplitude = fake.pyfloat(min_value=0.1, max_value=0.9)
        assert _settings(amplitude=amplitude).is_disabled() is False

    def test_max_amplitude_is_enabled(self):
        assert _settings(amplitude=1.0).is_disabled() is False


# ---------------------------------------------------------------------------
# Block C — a_d_envelope()
# ---------------------------------------------------------------------------


class TestADEnvelopeAssertions:
    def test_rejects_time_below_start(self):
        with pytest.raises(AssertionError):
            _ = a_d_envelope(_settings(), TIME_START - 0.001)

    def test_rejects_time_above_end(self):
        with pytest.raises(AssertionError):
            _ = a_d_envelope(_settings(), TIME_END + 0.001)


class TestADEnvelopeZeroRegions:
    def test_zero_before_attack_window(self):
        attack = fake.pyfloat(min_value=0.1, max_value=TIME_MIDPOINT - 0.01)
        settings = _settings(attack=attack)
        # Pick a time that is safely before the attack window opens
        attack_start = TIME_MIDPOINT - attack
        if attack_start <= TIME_START:
            pytest.skip("attack fills entire pre-midpoint region for this random value")
        time = fake.pyfloat(min_value=TIME_START, max_value=attack_start - 0.001)
        assert a_d_envelope(settings, time) == 0.0

    def test_zero_after_decay_window(self):
        decay = fake.pyfloat(min_value=0.1, max_value=TIME_MIDPOINT - 0.01)
        settings = _settings(decay=decay)
        decay_end = TIME_MIDPOINT + decay
        if decay_end >= TIME_END:
            pytest.skip("decay fills entire post-midpoint region for this random value")
        time = fake.pyfloat(min_value=decay_end + 0.001, max_value=TIME_END)
        assert a_d_envelope(settings, time) == 0.0

    def test_zero_at_time_start(self):
        # With attack well inside the window TIME_START is guaranteed to be silent
        settings = _settings(attack=fake.pyfloat(min_value=0.1, max_value=0.8))
        assert a_d_envelope(settings, TIME_START) == 0.0

    def test_zero_at_time_end(self):
        settings = _settings(decay=fake.pyfloat(min_value=0.1, max_value=0.8))
        assert a_d_envelope(settings, TIME_END) == 0.0


class TestADEnvelopePeak:
    def test_peak_at_midpoint_equals_amplitude(self):
        amplitude = _random_amplitude_enabled()
        settings = _settings(amplitude=amplitude)
        assert a_d_envelope(settings, TIME_MIDPOINT) == pytest.approx(amplitude)


@pytest.mark.parametrize("amplitude", [0.0, 0.005, AMPLITUDE_LOWER_CUTOFF])
class TestADEnvelopeDisabledAlwaysZero:
    def test_disabled_returns_zero(self, amplitude: float):
        settings = _settings(amplitude=amplitude)
        time = fake.pyfloat(min_value=TIME_START, max_value=TIME_END)
        assert a_d_envelope(settings, time) == 0.0


class TestADEnvelopeZeroAttackDecay:
    def test_near_zero_attack_just_before_midpoint_returns_zero(self):
        settings = _settings(attack=SLOPE_TIME_MIN, decay=_random_attack_decay())
        assert a_d_envelope(settings, TIME_MIDPOINT - SLOPE_TIME_MIN) == 0.0

    def test_near_zero_decay_just_after_midpoint_returns_zero(self):
        settings = _settings(attack=_random_attack_decay(), decay=SLOPE_TIME_MIN)
        assert a_d_envelope(settings, TIME_MIDPOINT + SLOPE_TIME_MIN) == 0.0


class TestADEnvelopeOutputRange:
    def test_output_in_range(self):
        settings = _settings()
        time = fake.pyfloat(min_value=TIME_START, max_value=TIME_END)
        result = a_d_envelope(settings, time)
        assert 0.0 <= result <= settings.amplitude + 1e-9


class TestADEnvelopeAmplitudeScaling:
    def test_amplitude_scales_linearly(self):
        # Use a time that is guaranteed to land inside the envelope window.
        # Attack and decay each span 0.3 units, so the window is [0.7, 1.3].
        attack = 0.3
        decay = 0.3
        shape = _random_shape()
        # Pick a time inside the window (not exactly at midpoint to avoid
        # the trivial case where both values are just amplitude).
        time = fake.pyfloat(
            min_value=TIME_MIDPOINT - attack + 0.05, max_value=TIME_MIDPOINT - 0.05
        )

        amplitude_a = fake.pyfloat(
            min_value=AMPLITUDE_LOWER_CUTOFF + 0.05, max_value=0.45
        )
        amplitude_b = amplitude_a * 2.0

        v_a = a_d_envelope(
            _settings(attack=attack, decay=decay, shape=shape, amplitude=amplitude_a),
            time,
        )
        v_b = a_d_envelope(
            _settings(attack=attack, decay=decay, shape=shape, amplitude=amplitude_b),
            time,
        )

        assert v_a > 0.0, "Expected non-zero value at chosen time"
        assert v_b / v_a == pytest.approx(2.0)


# ---------------------------------------------------------------------------
# Block D — offset_envelopes()
# ---------------------------------------------------------------------------


class TestOffsetEnvelopes:
    def test_returns_correct_count(self):
        n = fake.pyint(min_value=1, max_value=8)
        settings_list = [_settings() for _ in range(n)]
        interval = fake.pyfloat(min_value=0.01, max_value=0.5)
        time = fake.pyfloat(min_value=TIME_START, max_value=TIME_END)
        result = offset_envelopes(settings_list, interval, time)
        assert len(result) == n

    def test_env_times_in_range(self):
        n = fake.pyint(min_value=1, max_value=8)
        settings_list = [_settings() for _ in range(n)]
        interval = fake.pyfloat(min_value=0.01, max_value=0.5)
        time = fake.pyfloat(min_value=TIME_START, max_value=TIME_END)
        for status in offset_envelopes(settings_list, interval, time):
            assert TIME_START <= status.time < TIME_END + 1e-12

    def test_wrapping_correctness(self):
        """Each envelope i has env_time = (time - interval * i) % TIME_END."""
        time = 0.1
        interval = 0.5
        n = 4
        settings_list = [_settings() for _ in range(n)]
        result = offset_envelopes(settings_list, interval, time)
        for i, status in enumerate(result):
            expected = (time - interval * i) % TIME_END
            assert status.time == pytest.approx(expected)


# ---------------------------------------------------------------------------
# Block E — combine_envelopes()
# ---------------------------------------------------------------------------


def _disabled_settings() -> EnvelopeSettings:
    return _settings(amplitude=0.0)


def _enabled_settings() -> EnvelopeSettings:
    return _settings(amplitude=_random_amplitude_enabled())


class TestCombineEnvelopes:
    def test_all_disabled_returns_zero(self):
        n = fake.pyint(min_value=1, max_value=6)
        settings_list = [_disabled_settings() for _ in range(n)]
        interval = fake.pyfloat(min_value=0.1, max_value=0.4)
        time = fake.pyfloat(min_value=TIME_START, max_value=TIME_END)
        statuses = offset_envelopes(settings_list, interval, time)
        assert combine_envelopes(settings_list, statuses, time, combine_max) == 0.0

    def test_mismatched_lengths_raises(self):
        settings_list = [_settings() for _ in range(3)]
        statuses = [EnvelopeStatus(time=0.5, midpoint=1, value=0.5)] * 4  # wrong length
        with pytest.raises((ValueError, AssertionError)):
            _ = combine_envelopes(settings_list, statuses, 0.5, combine_max)

    def test_single_active_envelope_max(self):
        """One enabled envelope surrounded by disabled ones returns its value."""
        enabled = _enabled_settings()
        disabled = _disabled_settings()
        settings_list = [disabled, enabled, disabled]
        interval = 0.25
        time = fake.pyfloat(min_value=TIME_START, max_value=TIME_END)
        statuses = offset_envelopes(settings_list, interval, time)

        # The expected value is whatever the enabled envelope produces
        expected = statuses[1].value
        result = combine_envelopes(settings_list, statuses, time, combine_max)
        assert result == pytest.approx(expected)

    def test_single_active_envelope_linear(self):
        """After the single-active short-circuit fix, linear combiner must not
        raise ZeroDivisionError and must return the single envelope's value."""
        enabled = _enabled_settings()
        disabled = _disabled_settings()
        settings_list = [disabled, enabled, disabled]
        interval = 0.25
        time = fake.pyfloat(min_value=TIME_START, max_value=TIME_END)
        statuses = offset_envelopes(settings_list, interval, time)

        expected = statuses[1].value
        result = combine_envelopes(
            settings_list, statuses, time, combine_interpolate_linear
        )
        assert result == pytest.approx(expected)

    def test_disabled_envelope_is_skipped(self):
        """With two enabled envelopes flanking a disabled one, the disabled
        one must not participate in the combination."""
        # Three envelopes at equal spacing; disable the middle one.
        amplitude_left = fake.pyfloat(min_value=0.3, max_value=0.5)
        amplitude_right = fake.pyfloat(min_value=0.3, max_value=0.5)

        left_s = _settings(amplitude=amplitude_left)
        middle_s = _disabled_settings()
        right_s = _settings(amplitude=amplitude_right)

        settings_list = [left_s, middle_s, right_s]
        interval = INTERVAL_MAX  # evenly spaced within the allowed interval range

        # We need two non-disabled envelopes in the active list.
        # Sweep a few time values and verify output is never from the middle envelope.
        for _ in range(20):
            time = fake.pyfloat(min_value=TIME_START, max_value=TIME_END)
            statuses = offset_envelopes(settings_list, interval, time)
            combined = combine_envelopes(settings_list, statuses, time, combine_max)
            # The middle envelope is always disabled, so its value is 0.
            # The combined result must match what we'd get ignoring the middle one.
            only_active = [s for s in settings_list if not s.is_disabled()]
            only_status = [
                st
                for s, st in zip(settings_list, statuses, strict=True)
                if not s.is_disabled()
            ]
            expected = combine_envelopes(only_active, only_status, time, combine_max)
            assert combined == pytest.approx(expected)


# ---------------------------------------------------------------------------
# Block F — combine_max() and combine_interpolate_linear()
# ---------------------------------------------------------------------------


class TestCombineMax:
    @pytest.mark.parametrize(
        ("left_value", "right_value"),
        [(0.3, 0.7), (0.7, 0.3), (0.5, 0.5)],
    )
    def test_returns_higher_value(self, left_value: float, right_value: float):
        left = _status(time=0.5, value=left_value)
        right = _status(time=1.5, value=right_value)
        assert combine_max(left, right) == max(left_value, right_value)

    def test_equal_values_returns_that_value(self):
        v = fake.pyfloat(min_value=0.01, max_value=0.99)
        left = _status(time=0.5, value=v)
        right = _status(time=1.5, value=v)
        assert combine_max(left, right) == pytest.approx(v)


class TestCombineInterpolateLinear:
    def test_midpoint_equidistant_interpolation(self):
        # left.time=0.5, right.time=1.5 → weight=(1.0-0.5)/(1.5-0.5)=0.5
        left = _status(time=0.5, value=0.0)
        right = _status(time=1.5, value=1.0)
        assert combine_interpolate_linear(left, right) == pytest.approx(0.5)

    def test_output_in_value_range(self):
        left_time = fake.pyfloat(min_value=TIME_START, max_value=TIME_MIDPOINT - 0.05)
        right_time = fake.pyfloat(min_value=TIME_MIDPOINT + 0.05, max_value=TIME_END)
        lv = fake.pyfloat(min_value=0.01, max_value=0.99)
        rv = fake.pyfloat(min_value=0.01, max_value=0.99)
        result = combine_interpolate_linear(
            _status(left_time, lv), _status(right_time, rv)
        )
        assert min(lv, rv) - 1e-9 <= result <= max(lv, rv) + 1e-9

    def test_equal_values_returns_that_value(self):
        v = fake.pyfloat(min_value=0.01, max_value=0.99)
        left_time = fake.pyfloat(min_value=TIME_START, max_value=TIME_MIDPOINT - 0.05)
        right_time = fake.pyfloat(min_value=TIME_MIDPOINT + 0.05, max_value=TIME_END)
        result = combine_interpolate_linear(
            _status(left_time, v), _status(right_time, v)
        )
        assert result == pytest.approx(v)
